repayment_schedule:
  days_in_month: 30
  days_in_year: 360

logging:
  level:
    org.springframework: ERROR
    de.demo.plangenerator: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %X{correlationID} -  %msg%n"
